###########################################################
#         makefile for the elliptecCtrl unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = elliptecCtrl_test elliptecCtrl_indi_test

include ../../../tests/magAOX_test.mk
