###########################################################
#       makefile for the closedLoopIndi unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = closedLoopIndi_test closedLoopIndi_indi_test

include ../../../tests/magAOX_test.mk
