
allall: all

# Shared WCC support headers, listed so a change to one rebuilds the app.
OTHER_HEADERS = ../wccCommon/wccUnits.hpp \
                ../wccCommon/wccSkyWCS.hpp \
                ../wccCommon/wccStarCatalog.hpp \
                ../wccCommon/wccFocalPlane.hpp \
                ../wccCommon/wccAstrometry.hpp \
                ../wccCommon/wccJSON.hpp \
                ../wccCommon/wccVisit.hpp \
                ../wccCommon/wccVisitIndi.hpp \
                ../wccCommon/wccIndiRate.hpp \
                ../wccCommon/wccNumeric.hpp \
                ../wccCommon/wccSensorConfig.hpp

TARGET = wccCtrl

include ../../Make/magAOXApp.mk
