[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hamCtrl"
description = "Python INDI device for controlling the Hamamatsu 15550-22UP Camera"
version = "1.0.1.dev"
dependencies = [
    "xconf",
    "purepyindi2",
]
authors = [
    {name = "Stephanie F. Rinaldi", email = "srinaldi@arizona.edu"},
    {name = "Adam Schilperoort", email = "adamschilperoort@arizona.edu"}
]

[project.scripts]
hamCtrl = "xapp.hamCtrl:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["xapp*"]
