###########################################################
#          makefile for the sparkleClock unit tests       #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = sparkleClock_test

include ../../../tests/magAOX_test.mk
