###########################################################
#        makefile for the t2wOffloader unit tests         #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = t2wOffloader_test t2wOffloader_indi_test

include ../../../tests/magAOX_test.mk
