###########################################################
#          makefile for the dmPokeXCorr unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = dmPokeXCorr_test dmPokeXCorr_indi_test

include ../../../tests/magAOX_test.mk
