###########################################################
#          makefile for the mcp3208Ctrl unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = mcp3208Ctrl_test

include ../../../tests/magAOX_test.mk
