###########################################################
#          makefile for the xInstGraph unit tests         #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = xInstGraph_test \
        ../xigNodes/tests/xigNode_test \
        ../xigNodes/tests/fsmNode_test \
        ../xigNodes/tests/indiPropNode_test \
        ../xigNodes/tests/pwrOnOffNode_test \
        ../xigNodes/tests/staticNode_test \
        ../xigNodes/tests/stdMotionNode_test

include ../../../tests/magAOX_test.mk
