###########################################################
#         makefile for the smc100ccCtrl unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = smc100ccCtrl_test smc100ccCtrl_indi_test

include ../../../tests/magAOX_test.mk
