###########################################################
#          makefile for the cred2Ctrl unit tests          #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = cred2Ctrl_test cred2Ctrl_lifecycle_test cred2Utils_test

include ../../../tests/magAOX_test.mk
