###########################################################
#         makefile for the streamWriter unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = streamWriter_test streamWriterSizing_test streamWriter_lifecycle_test

include ../../../tests/magAOX_test.mk
