###########################################################
#          makefile for the adcTracker unit tests         #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = adcTracker_test

include ../../../tests/magAOX_test.mk
