#!/bin/bash

echo "setting block leaks to 0.98 above block 6"

setINDI -n "hogainctrl.block06_multcoeff.target=0.98"
setINDI -n "hogainctrl.block07_multcoeff.target=0.98"
setINDI -n "hogainctrl.block08_multcoeff.target=0.98"
setINDI -n "hogainctrl.block09_multcoeff.target=0.98"
setINDI -n "hogainctrl.block10_multcoeff.target=0.98"
setINDI -n "hogainctrl.block11_multcoeff.target=0.98"
setINDI -n "hogainctrl.block12_multcoeff.target=0.98"
setINDI -n "hogainctrl.block13_multcoeff.target=0.98"
setINDI -n "hogainctrl.block14_multcoeff.target=0.98"
setINDI -n "hogainctrl.block15_multcoeff.target=0.98"
setINDI -n "hogainctrl.block17_multcoeff.target=0.98"
setINDI -n "hogainctrl.block18_multcoeff.target=0.98"
setINDI -n "hogainctrl.block19_multcoeff.target=0.98"
setINDI -n "hogainctrl.block20_multcoeff.target=0.98"