#!/usr/bin/env bash
set -ex
# If not started as root, sudo yourself
if [[ "$EUID" != 0 ]]; then
    sudo -H bash -l $0 "$@"
    exit $?
fi
if [[ $(hostname) != "exao1" ]]; then
    echo "Must run on exao1"
    exit 1
fi
if [[ -z "$1" ]]; then
    dest=/mnt/backup
else
    dest="$1"
fi

declare -a dataFolders=("opt/MagAOX/logs" "opt/MagAOX/rawimages" "opt/MagAOX/telem" "opt/MagAOX/cacao")

if ! mount | grep -q "on $dest"; then
    echo "External drive mount appears not to be active for $dest"
    exit 1
fi
for remote in icc rtc; do
    for folder in "${dataFolders[@]}"; do
        if ! mount | grep -q "on /srv/$remote/$folder"; then
            echo "NFS mount appears not to be active for on /srv/$remote/$folder"
            exit 1
        fi
    done
done

rsyncWithOptions="rsync -a --info=progress2"

for remote in rtc icc; do
    for folder in "${dataFolders[@]}"; do
        mkdir -p "$dest/$remote/$folder/"
        $rsyncWithOptions "/srv/$remote/$folder/" "$dest/$remote/$folder/"
    done
done

for folder in "${dataFolders[@]}"; do
    mkdir -p "$dest/aoc/$folder"
    $rsyncWithOptions "/$folder/" "$dest/aoc/$folder"
done
for home in /home/*; do
    if [[ $(basename $home) != "data" ]]; then
        mkdir -p "$dest/aoc/$home/"
        $rsyncWithOptions "$home/" "$dest/aoc/$home/"
    fi
done
