#!/usr/bin/env python
import sys
import requests
import datetime
from datetime import datetime, timedelta, timezone
import json
import math
import ssl

scopes = ['dimm', 'clay', 'baade']

def retrieve_one(name):
    now = datetime.datetime.now(timezone.utc)
    start_ts = (now - timedelta(minutes=1)).isoformat()
    end_ts = now.isoformat()

    req = requests.get(
        "https://weather-dev.lco.cl/api/metrics/seeing",
        params={
            'source': name,
            'start_ts': start_ts,
            'end_ts': end_ts,
        }
    )
    seeing_points = req.json()
    latest_seeing_point = seeing_points.sort(key=lambda x: x['ts'], reverse=True)[0]
    
    req = requests.get(
        "https://weather-dev.lco.cl/api/status/telescope_data",
        params={
            'output': 'raw',
            'window': '1min',
            'aggregation': 'min',
            'source': name,
            'start_ts': start_ts,
            'end_ts': end_ts,
        }
    )
    pointing_points = req.json()
    latest_pointing_point = pointing_points.sort(key=lambda x: x['ts'], reverse=True)[0]
    return latest_seeing_point, latest_pointing_point
    
def main(debug):
    for name in ['dimm', 'clay', 'baade']:
        outfile_name = {'dimm': 'dimm', 'clay': 'mag2', 'baade': 'mag2'}[name]
        try:
            point = retrieve_one(name)
        except Exception as e:
            print(e, file=sys.stderr)
            point = {
                'tm': '1970-01-01 00:00:00',
                'el': 0.0,
                'fw': -1.0,
            }
        with open(f"/tmp/{outfile_name}.tsv", 'w') as fh:
            fh.write(f"datetime fwhm elevation\n")
            fh.write(f"{point['tm']} {point['fw']} {point['el']}\n")
            if debug:
                print(outfile_name)
                print("datetime fwhm elevation")
                print(f"{point['tm']} {point['fw']} {point['el']}")
                print()
    return 0

if __name__ == "__main__":
    debug = sys.argv[-1] == '--debug'
    sys.exit(main(debug))
