#!/usr/bin/env python
import sys
import urllib.request
import urllib.parse
import datetime
from datetime import datetime, timedelta, timezone
import json

scopes = ['dimm', 'clay', 'baade']

def retrieve_one(name):
    now = datetime.now(timezone.utc)
    start_ts = (now - timedelta(minutes=1)).isoformat()
    end_ts = now.isoformat()

    # First request for seeing
    params = urllib.parse.urlencode({
        'source': name,
        'start_ts': start_ts,
        'end_ts': end_ts,
    })
    url = f"https://weather-dev.lco.cl/api/metrics/seeing?{params}"
    req = urllib.request.Request(url, headers={
        'Referer': 'https://weather-dev.lco.cl/stations/magellan',
    })
    with urllib.request.urlopen(req) as response:
        seeing_data = json.loads(response.read().decode('utf-8'))
    seeing_points = seeing_data['results']
    latest_seeing_point = sorted(seeing_points, key=lambda x: x['ts'], reverse=True)[0]

    return latest_seeing_point

def main():
    scopes = ['dimm', 'baade', 'clay']
    with open(f"/tmp/query_seeing.txt", "w") as fh:
        outstr = "utcdate utctime scope fwhm_corr"
        fh.write(outstr + "\n")
        for name in scopes:
            seeing = retrieve_one(name)
            utcdate, utctime_usec = seeing['ts'].split('T')
            utctime, _ = utctime_usec.split('.')[0]
            outstr = f"{utcdate} {utctime} {seeing['seeing']}"
            print(outstr)
            fh.write(outstr + "\n")

    return 0

if __name__ == "__main__":
    debug = sys.argv[-1] == '--debug'
    sys.exit(main(debug))
