###########################################################
#          makefile for the xt1121DCDU unit tests         #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = xt1121DCDU_test

include ../../../tests/magAOX_test.mk
