###########################################################
#          makefile for the ocam2KCtrl unit tests         #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = ocam2KCtrl_test ocam2KCtrl_lifecycle_test ocamUtils_test

include ../../../tests/magAOX_test.mk
