###########################################################
#       makefile for the stateRuleEngine unit tests       #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = stateRuleEngine_test indiCompRules_test indiCompRuleConfig_test

include ../../../tests/magAOX_test.mk
