###########################################################
#          makefile for the dmPokeCenter unit tests       #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = dmPokeCenter_test dmPokeCenter_indi_test

include ../../../tests/magAOX_test.mk
