channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - astropy
  - ipython
  - ipywidgets
  - notebook
  - numpy
  - scipy
  - matplotlib
  - numexpr
  - Pillow
  - scikit-image
  - pip
  - nb_conda_kernels
  - pytest
  - psutil
  - cupy
  - line_profiler
  - pyserial
  # video streaming
  - cffi
  - cryptography
  - av
  - pyee
  - ffmpeg
  - libopus
  - libvpx
  # web ui
  - nodejs
  - yarn
  - websockets
  - ujson
  - uvloop
  # hcipy deps available in conda
  - asdf
  - pyyaml
  - imageio
  - xxhash
  # for cacao
  - pybind11 

  - pip:
      - hcipy
      - poppy
      # web ui
      - aiortc
      - python-engineio
      - python-socketio
      - starlette
      - uvicorn
