
allall: all

# Shared WCC support headers, listed so a change to one rebuilds the app.
OTHER_HEADERS = ../wccCommon/wccUnits.hpp \
                ../wccCommon/wccSkyWCS.hpp \
                ../wccCommon/wccFocalPlane.hpp \
                ../wccCommon/wccSensorModel.hpp \
                ../wccCommon/wccVisit.hpp \
                ../wccCommon/wccVisitIndi.hpp \
                ../wccCommon/wccIndiRate.hpp \
                ../wccCommon/wccNumeric.hpp \
                ../wccCommon/wccPointingShmim.hpp

TARGET = telescopeSim

include ../../Make/magAOXApp.mk
