###########################################################
#        makefile for the zaberLowLevel unit tests        #
#                                                         #
# `make` builds the tests and `make test` builds and      #
# runs them.  See README.md and tests/magAOX_test.mk.     #
###########################################################

TESTS = zaberLowLevel_test zaberStage_test zaberUtils_test

include ../../../tests/magAOX_test.mk
